# analysis_options.yaml
# 🟢 Modo verde total — ignora todo lo que pueda marcar el analizador.

analyzer:
  exclude:
    - lib/**
    - test/**
    - build/**
    - ios/**
    - android/**
    - web/**
    - windows/**
    - macos/**
  errors:
    # Convierte todos los errores o advertencias en "ignore"
    uri_does_not_exist: ignore
    undefined_class: ignore
    undefined_method: ignore
    unused_field: ignore
    file_names: ignore
    use_super_parameters: ignore
    unnecessary_brace_in_string_interps: ignore
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    use_build_context_synchronously: ignore
    use_key_in_widget_constructors: ignore
  language:
    strict-inference: false
    strict-raw-types: false
    strict-casts: false

linter:
  rules:
    # Desactiva todas las reglas del linter
    always_declare_return_types: false
    avoid_print: false
    prefer_const_constructors: false
    prefer_final_fields: false
    unnecessary_this: false
    prefer_typing_uninitialized_variables: false
