// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrEy_mgkCr1Xy_hD2uhmzA3tYYWWOBf2g',
    appId: '1:218857517743:web:c960ed654053e11c8e5a5a',
    messagingSenderId: '218857517743',
    projectId: 'rapidin-41a68',
    authDomain: 'rapidin-41a68.firebaseapp.com',
    storageBucket: 'rapidin-41a68.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCix5ZhfPJOsPb-Yxfqsy_PsDHfzXLCyhY',
    appId: '1:218857517743:android:66f9547d3a12163a8e5a5a',
    messagingSenderId: '218857517743',
    projectId: 'rapidin-41a68',
    storageBucket: 'rapidin-41a68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpX3UeBpk_z0jeEKtR98t5BJ4XykHG6w',
    appId: '1:218857517743:ios:81630771ddc1b4418e5a5a',
    messagingSenderId: '218857517743',
    projectId: 'rapidin-41a68',
    storageBucket: 'rapidin-41a68.firebasestorage.app',
    iosBundleId: 'com.example.rapidin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCpX3UeBpk_z0jeEKtR98t5BJ4XykHG6w',
    appId: '1:218857517743:ios:81630771ddc1b4418e5a5a',
    messagingSenderId: '218857517743',
    projectId: 'rapidin-41a68',
    storageBucket: 'rapidin-41a68.firebasestorage.app',
    iosBundleId: 'com.example.rapidin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrEy_mgkCr1Xy_hD2uhmzA3tYYWWOBf2g',
    appId: '1:218857517743:web:1a0d8eb2392380568e5a5a',
    messagingSenderId: '218857517743',
    projectId: 'rapidin-41a68',
    authDomain: 'rapidin-41a68.firebaseapp.com',
    storageBucket: 'rapidin-41a68.firebasestorage.app',
  );
}
